# Generated by Django 2.1.7 on 2019-02-20 03:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.TextField()),
                ('ename', models.TextField()),
                ('dob', models.DateTimeField(default=datetime.datetime(2019, 2, 20, 3, 55, 1, 650002, tzinfo=utc))),
            ],
        ),
    ]
