# Generated by Django 2.1.7 on 2019-02-20 04:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 4, 3, 14, 775207, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emp',
            name='eid',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='emp',
            name='ename',
            field=models.CharField(max_length=20),
        ),
    ]
