# Generated by Django 2.1.7 on 2019-03-06 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20190220_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='dob',
        ),
    ]
