# Generated by Django 2.1.7 on 2019-03-07 05:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_emp_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=50, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='emp',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 7, 5, 31, 12, 882, tzinfo=utc)),
        ),
    ]
