# Generated by Django 2.1.7 on 2019-03-07 05:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_auto_20190307_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 7, 5, 35, 7, 762367, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emp',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=50, verbose_name='E-Mail'),
        ),
    ]
